import { KYCRecord, DocumentSection } from '@/types/kyc';
import { SupportTicket } from '@/types/support';
import { Deployment, EnvironmentConfig } from '@/types/deployment';
import { AuditLog } from '@/types/audit';

export const mockKYCRecords: KYCRecord[] = [
  {
    id: 'kyc-001',
    userId: 'usr-12345',
    userName: 'Sarah Chen',
    email: 'sarah.chen@example.com',
    riskScore: 75,
    status: 'pending',
    submittedDate: '2026-09-10T14:30:00Z',
    documentType: 'passport',
    documentStatus: 'pending',
    country: 'Singapore',
    priority: 'high',
  },
  {
    id: 'kyc-002',
    userId: 'usr-12346',
    userName: 'Marcus Johnson',
    email: 'm.johnson@example.com',
    riskScore: 25,
    status: 'pending',
    submittedDate: '2026-09-11T09:15:00Z',
    documentType: 'drivers_license',
    documentStatus: 'verified',
    country: 'United States',
    priority: 'low',
  },
  {
    id: 'kyc-003',
    userId: 'usr-12347',
    userName: 'Elena Rodriguez',
    email: 'elena.r@example.com',
    riskScore: 90,
    status: 'reviewing',
    submittedDate: '2026-09-12T08:00:00Z',
    documentType: 'national_id',
    documentStatus: 'pending',
    country: 'Spain',
    priority: 'high',
  },
  {
    id: 'kyc-004',
    userId: 'usr-12348',
    userName: 'James Wilson',
    email: 'j.wilson@example.com',
    riskScore: 45,
    status: 'pending',
    submittedDate: '2026-09-11T16:45:00Z',
    documentType: 'passport',
    documentStatus: 'verified',
    country: 'United Kingdom',
    priority: 'medium',
  },
  {
    id: 'kyc-005',
    userId: 'usr-12349',
    userName: 'Aisha Patel',
    email: 'aisha.p@example.com',
    riskScore: 60,
    status: 'pending',
    submittedDate: '2026-09-12T10:30:00Z',
    documentType: 'passport',
    documentStatus: 'pending',
    country: 'India',
    priority: 'medium',
  },
];

export const mockDocumentSections: DocumentSection[] = [
  {
    id: 'section-1',
    title: 'Personal Information',
    pageNumber: 1,
    description: 'Name, date of birth, and nationality details',
  },
  {
    id: 'section-2',
    title: 'Address Verification',
    pageNumber: 2,
    description: 'Current residential address and proof of address',
  },
  {
    id: 'section-4',
    title: 'Declaration & Signature',
    pageNumber: 4,
    description: 'Applicant signature and photograph',
  },
];

export const mockSupportTickets: SupportTicket[] = [
  {
    id: 'tkt-001',
    userId: 'usr-12345',
    userName: 'Sarah Chen',
    email: 'sarah.chen@example.com',
    subject: 'Payment not reflected in account',
    category: 'payment',
    status: 'open',
    priority: 'high',
    createdDate: '2026-09-12T09:00:00Z',
    lastUpdated: '2026-09-12T09:00:00Z',
    assignedTo: 'agent-001',
    description: 'I made a payment of $5,000 yesterday but it still shows as pending in my account.',
    messages: [
      {
        id: 'msg-001',
        userId: 'usr-12345',
        userName: 'Sarah Chen',
        message: 'I made a payment of $5,000 yesterday but it still shows as pending in my account.',
        timestamp: '2026-09-12T09:00:00Z',
        isInternal: false,
      },
    ],
  },
  {
    id: 'tkt-002',
    userId: 'usr-12346',
    userName: 'Marcus Johnson',
    email: 'm.johnson@example.com',
    subject: 'Unable to upload ID documents',
    category: 'technical',
    status: 'in_progress',
    priority: 'medium',
    createdDate: '2026-09-11T14:30:00Z',
    lastUpdated: '2026-09-12T08:15:00Z',
    assignedTo: 'agent-002',
    description: 'Keep getting error when trying to upload my passport for KYC verification.',
    messages: [
      {
        id: 'msg-002',
        userId: 'usr-12346',
        userName: 'Marcus Johnson',
        message: 'Keep getting error when trying to upload my passport for KYC verification.',
        timestamp: '2026-09-11T14:30:00Z',
        isInternal: false,
      },
      {
        id: 'msg-003',
        userId: 'agent-002',
        userName: 'Support Agent',
        message: 'Could you please try clearing your browser cache and attempt the upload again?',
        timestamp: '2026-09-12T08:15:00Z',
        isInternal: false,
      },
    ],
  },
  {
    id: 'tkt-003',
    userId: 'usr-12352',
    userName: 'Michael Brown',
    email: 'm.brown@example.com',
    subject: 'Account locked due to failed login attempts',
    category: 'account',
    status: 'open',
    priority: 'urgent',
    createdDate: '2026-09-12T07:45:00Z',
    lastUpdated: '2026-09-12T07:45:00Z',
    description: 'My account has been locked after several failed login attempts. I need access urgently.',
    messages: [
      {
        id: 'msg-004',
        userId: 'usr-12352',
        userName: 'Michael Brown',
        message: 'My account has been locked after several failed login attempts. I need access urgently.',
        timestamp: '2026-09-12T07:45:00Z',
        isInternal: false,
      },
    ],
  },
  {
    id: 'tkt-004',
    userId: 'usr-12353',
    userName: 'Emma Garcia',
    email: 'emma.g@example.com',
    subject: 'Question about transaction limits',
    category: 'compliance',
    status: 'resolved',
    priority: 'low',
    createdDate: '2026-09-10T11:00:00Z',
    lastUpdated: '2026-09-11T16:30:00Z',
    assignedTo: 'agent-001',
    description: 'What are the current transaction limits for verified accounts?',
    messages: [
      {
        id: 'msg-005',
        userId: 'usr-12353',
        userName: 'Emma Garcia',
        message: 'What are the current transaction limits for verified accounts?',
        timestamp: '2026-09-10T11:00:00Z',
        isInternal: false,
      },
      {
        id: 'msg-006',
        userId: 'agent-001',
        userName: 'Support Agent',
        message: 'For verified accounts, the daily limit is $10,000 and monthly limit is $50,000.',
        timestamp: '2026-09-11T16:30:00Z',
        isInternal: false,
      },
    ],
  },
  {
    id: 'tkt-005',
    userId: 'usr-12354',
    userName: 'Robert Lee',
    email: 'r.lee@example.com',
    subject: 'Feature request: recurring payments',
    category: 'other',
    status: 'open',
    priority: 'low',
    createdDate: '2026-09-12T06:00:00Z',
    lastUpdated: '2026-09-12T06:00:00Z',
    description: 'Would like to suggest adding recurring payment functionality.',
    messages: [
      {
        id: 'msg-007',
        userId: 'usr-12354',
        userName: 'Robert Lee',
        message: 'Would like to suggest adding recurring payment functionality.',
        timestamp: '2026-09-12T06:00:00Z',
        isInternal: false,
      },
    ],
  },
];

export const environmentConfigs: EnvironmentConfig[] = [
  {
    name: 'testing',
    displayName: 'Testing',
    color: 'bg-purple-100 text-purple-800',
    url: 'https://testing.fintech.com',
  },
  {
    name: 'staging',
    displayName: 'Staging',
    color: 'bg-yellow-100 text-yellow-800',
    url: 'https://staging.fintech.com',
  },
  {
    name: 'production',
    displayName: 'Production',
    color: 'bg-green-100 text-green-800',
    url: 'https://app.fintech.com',
  },
];

export const mockDeployments: Deployment[] = [
  {
    id: 'deploy-001',
    appName: 'KYC Review Queue',
    environment: 'production',
    version: 'v2.4.1',
    status: 'running',
    deployedAt: '2026-09-10T14:30:00Z',
    deployedBy: 'devops-001',
    commitHash: 'a1b2c3d',
    description: 'Production deployment with PDF navigation feature',
  },
  {
    id: 'deploy-002',
    appName: 'KYC Review Queue',
    environment: 'staging',
    version: 'v2.5.0',
    status: 'running',
    deployedAt: '2026-09-11T09:15:00Z',
    deployedBy: 'devops-001',
    commitHash: 'e4f5g6h',
    description: 'Staging deployment with RBAC improvements',
  },
  {
    id: 'deploy-003',
    appName: 'KYC Review Queue',
    environment: 'testing',
    version: 'v2.6.0-dev',
    status: 'deploying',
    deployedAt: '2026-09-12T08:00:00Z',
    deployedBy: 'devops-001',
    commitHash: 'x7y8z9a',
    description: 'Testing deployment with enhanced PDF viewer',
  },
  {
    id: 'deploy-004',
    appName: 'Support Ticketing',
    environment: 'production',
    version: 'v1.8.3',
    status: 'running',
    deployedAt: '2026-09-09T16:45:00Z',
    deployedBy: 'devops-001',
    commitHash: 'i7j8k9l',
    description: 'Production deployment with message threading',
  },
  {
    id: 'deploy-005',
    appName: 'Support Ticketing',
    environment: 'staging',
    version: 'v1.9.0',
    status: 'running',
    deployedAt: '2026-09-11T10:30:00Z',
    deployedBy: 'devops-001',
    commitHash: 'm0n1o2p',
    description: 'Staging deployment with AI-powered responses',
  },
  {
    id: 'deploy-006',
    appName: 'Support Ticketing',
    environment: 'testing',
    version: 'v1.10.0-dev',
    status: 'failed',
    deployedAt: '2026-09-12T06:00:00Z',
    deployedBy: 'devops-001',
    commitHash: 'q3r4s5t',
    description: 'Failed deployment - database migration issue',
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: 'audit-001',
    timestamp: '2026-09-12T14:30:00Z',
    userId: 'usr-001',
    userName: 'Admin User',
    role: 'admin',
    action: 'approve_kyc',
    entityType: 'kyc',
    entityId: 'kyc-001',
    entityName: 'Sarah Chen',
    details: 'Approved KYC application with risk score 45',
    ipAddress: '192.168.1.100',
  },
  {
    id: 'audit-002',
    timestamp: '2026-09-12T14:25:00Z',
    userId: 'usr-002',
    userName: 'KYC Reviewer A',
    role: 'kyc_reviewer',
    action: 'reject_kyc',
    entityType: 'kyc',
    entityId: 'kyc-002',
    entityName: 'Marcus Johnson',
    details: 'Rejected KYC application - insufficient documentation',
    ipAddress: '192.168.1.101',
  },
  {
    id: 'audit-003',
    timestamp: '2026-09-12T14:20:00Z',
    userId: 'usr-003',
    userName: 'Support Agent B',
    role: 'support_agent',
    action: 'resolve_ticket',
    entityType: 'support',
    entityId: 'tkt-003',
    entityName: 'Account status inquiry',
    details: 'Resolved ticket for Emily Davis - account unlocked',
    ipAddress: '192.168.1.102',
  },
  {
    id: 'audit-004',
    timestamp: '2026-09-12T14:15:00Z',
    userId: 'usr-004',
    userName: 'Support Agent C',
    role: 'support_agent',
    action: 'assign_ticket',
    entityType: 'support',
    entityId: 'tkt-001',
    entityName: 'Payment not reflected in account',
    details: 'Assigned ticket to agent-001 for payment investigation',
    ipAddress: '192.168.1.103',
  },
  {
    id: 'audit-005',
    timestamp: '2026-09-12T14:10:00Z',
    userId: 'usr-005',
    userName: 'Admin User',
    role: 'admin',
    action: 'deploy_app',
    entityType: 'deployment',
    entityId: 'deploy-001',
    entityName: 'KYC Review Queue v2.4.1',
    details: 'Deployed KYC Review Queue v2.4.1 to production',
    ipAddress: '192.168.1.104',
  },
  {
    id: 'audit-006',
    timestamp: '2026-09-12T14:05:00Z',
    userId: 'usr-006',
    userName: 'DevOps A',
    role: 'devops',
    action: 'stop_deployment',
    entityType: 'deployment',
    entityId: 'deploy-006',
    entityName: 'Support Ticketing v1.10.0-dev',
    details: 'Stopped failed deployment due to database migration issue',
    ipAddress: '192.168.1.105',
  },
  {
    id: 'audit-007',
    timestamp: '2026-09-12T14:00:00Z',
    userId: 'usr-002',
    userName: 'KYC Reviewer A',
    role: 'kyc_reviewer',
    action: 'change_status',
    entityType: 'kyc',
    entityId: 'kyc-003',
    entityName: 'Emily Davis',
    details: 'Changed status from pending to reviewing',
    ipAddress: '192.168.1.106',
  },
  {
    id: 'audit-008',
    timestamp: '2026-09-12T13:55:00Z',
    userId: 'usr-003',
    userName: 'Support Agent B',
    role: 'support_agent',
    action: 'change_status',
    entityType: 'support',
    entityId: 'tkt-002',
    entityName: 'Unable to upload ID documents',
    details: 'Changed status from open to in_progress',
    ipAddress: '192.168.1.107',
  },
];